### ISSUE TITLE
mismatch of survey variables / values

### ISSUE THREAD

**Issue by jonathan-chin** [JaleelB/SNAP-Assistance-Tool#3]
in `features/Screener/hook/useVerifyEligibility.js`, there are references to `Household, # of people`. However, I think the SurveyJS variable is called `Household size`.

also, the value for `Household size` when it is just one person is `item1` instead of 1.

we should sync the variable names and values of the SurveyJS with our code.

**Comment by JaleelB** [comment]
When the data is returned at the end of the survey it shows "Household, #" for the size of the survey. I will definitely take a look though. 

As it relates to the variable names, Catherine is currently working on renaming them.

**Comment by jonathan-chin** [comment]
hmm, maybe I have an outdated SurveyJS json?
